### ISSUE TITLE
CI integration: allow adding [skip ci] to semantic-release commit

### ISSUE THREAD

**Issue by Sieboldianus** [relekang/python-semantic-release#153]
We've successfully implemented semantic-release in our Gitlab CI workflow on the `master-release` branch, passing GL_TOKEN through as a protected variable.

There's a minor inconvenience, when semantic-release pushes the new version to the branch within the CI job, it'll trigger the pipeline again (resulting in one needless CI run).

As far as I know, [semantic-release](https://github.com/semantic-release/git#usage) allows making use of the [[skip ci]](https://docs.gitlab.com/ee/ci/yaml/README.html#skipping-jobs) flag in semantic-release commit. I wonder if this is the only solution - then maybe it would make sense allowing to set a flag `--skip-ci` to python-semantic-release which would add `[skip ci]` to the version commit.

Here's our gitlab-ci.yml, for completeness:

```yml
build:
  image: python:alpine
  stage: build
  variables:
    GITLAB_CI : "true"
  script:
    - apk update && apk add git
    # checkout to release branch
    - git checkout -B "$CI_BUILD_REF_NAME" "$CI_BUILD_REF"
    - git config --global user.name "semantic-release (via GitlabCI)"
    - git config --global user.email "semantic-release@gitlab"
    # install python-semantic-release
    - pip install python-semantic-release
    # publish release
    - semantic-release publish
  only:
  - master-release
```
