### ISSUE TITLE
Move GitHub Action into main repository

### ISSUE THREAD

**Issue by AlphaMycelium** [relekang/python-semantic-release#196]
Do we think it is a good idea to move [psr-action](https://github.com/AlphaMycelium/psr-action) (Python Semantic Release for GitHub Actions) into a sub-directory within this repository, or should it be kept separate?

I am happy to make a pull request for this if we decide to go ahead with it. My separate repository would be archived and kept around to avoid breaking any existing setups.

## Pros

- More organised
- A specific version of Python Semantic Release can be loaded by tag or commit reference
- An update to the action can be released at the same time as any breaking changes

## Cons

- Versions prior to this change would not be available to use on Actions
- Anyone who has set up the action using my repository will need to update their configuration
- Cannot be published to GitHub Marketplace if we store it in a sub-directory

**Comment by AlphaMycelium** [comment]
This would make the workflow file look something like this:

```yaml
name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Python Semantic Release
      uses: relekang/python-semantic-release/action@v4.10.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pypi_username: ...
        pypi_password: ${{ secrets.PYPI_PASSWORD }}
```
