### ISSUE TITLE
Misleading information about protected branches setup

### ISSUE THREAD

**Issue by alekseik1** [relekang/python-semantic-release#311]
Hi! 
I recently tried to set up automated releases on GitHub Actions as prescribed in [official manual](https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html). My `master` branch is protected: it is required that a commit passes CI checks before it can be merged into master.

My CI pipelines has been constantly failing for all times with error `'remote: error: GH006: Protected branch update failed for refs/heads/master`. I created a personal access token with admin rights (it was actually my account PAT), saved to repo's secrets and passed it to GH action:
```yaml
with:
        github_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
```
but it did not work. Also, I found another issue here #274 addressing almost the same problem but proposed solution did not work out as well.

After some experiments I found out that an admin token should be also passed to `actions/checkout@v2` for it to have push access ([action homepage](https://github.com/actions/checkout)). So my final pipeline looks as follows:
```yaml
name: build and deploy

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        pypi_token: ${{ secrets.PYPI_API_TOKEN }}
```

This version works as expected: creates version commit with changelog if necessary, then pushes it to github, creates release on both GitHub and PyPi (the latter can be disabled in settings though).

I think it should be mentioned in docs that a personal access token should be passed to `checkout` action as well.

Thanks in advance.
