### ISSUE TITLE
semantic release publish fails

### ISSUE THREAD

**Issue by ShervinAbd92** [relekang/python-semantic-release#396]
## Current behavior

i am trying to use automatic semantic versioning with my github action workflow. it seems that everything is working fine until the publish section. i have my workflow set at following
```yaml
jobs:
  jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build --user
        pip install flake8 black wheel twine setuptools
        pip install .
        pip install -r requirements-dev.txt 
    - name: build a binary wheel & source tarball
      run: |
        python -m build --sdist --wheel --outdir dist/ .
    - name: twine check
      run: twine check dist/*
  release:
    runs-on: ubuntu-latest
    concurrency: release
    needs: deploy
    steps:
    - uses: actions/checkout@v2
      with:
        ref : 'main'
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pypi_token: ${{ secrets.PYPI_PASSWORD }}
```
and the report i get from release part: 
```
/semantic-release/action.sh: line 3: set: -l: invalid option
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
debug: get_current_version_by_config_file()
debug: Parsing current version: path=PosixPath('setup.py') pattern='__version__ *[:=] *["\\\'](\\d+\\.\\d+(?:\\.\\d+)?)["\\\']' num_matches=1
debug: Regex matched version: 0.2.0
debug: get_current_version_by_config_file -> 0.2.0
debug: evaluate_version_bump('0.2.0', None)
debug: Reference v0.2.0 does not exist, considering entire history
debug: parse_commit_message('fix: chabged the source for semantic release')
debug: parse_commit_message -> ParsedCommit(bump=1, type='fix', scope=None, descriptions=['chabged the source for semantic release'], breaking_descriptions=[])
debug: Commits found since last release: 1
debug: evaluate_version_bump -> patch
debug: get_new_version('0.2.0', 'patch')
debug: get_new_version -> 0.2.1
debug: get_repository_owner_and_name()
debug: get_repository_owner_and_name -> ('ShervinAbd92', 'fcdproc')
debug: Running publish on branch "main"
debug: checkout('"main"')
error: Cmd('git') failed due to: exit code(1)
error:   cmdline: git checkout "main"
error:   stderr: 'error: pathspec '"main"' did not match any file(s) known to git'
```
## Expected behavior

i would have expected it publish this version bump release on github, but it fails
Any suggestion as why this is happening or how to resolve it would be appreciated?

**Comment by danth** [comment]
It looks like you have included quotes in the branch, so Git is looking for `"main"` rather than `main`.

**Comment by ShervinAbd92** [comment]
you were completely right. once i removed the quotes the error was gone but then i got another error when uploading top pypi. i have created token on pypi for this project, so i dont understand why i get this error 
```
creating fcdproc-0.1.2
creating fcdproc-0.1.2/fcdproc
creating fcdproc-0.1.2/fcdproc.egg-info
creating fcdproc-0.1.2/fcdproc/interfaces
creating fcdproc-0.1.2/fcdproc/utils
creating fcdproc-0.1.2/fcdproc/workflow
copying files to fcdproc-0.1.2...
copying AUTHORS.rst -> fcdproc-0.1.2
copying CONTRIBUTING.rst -> fcdproc-0.1.2
copying LICENSE.txt -> fcdproc-0.1.2
copying MANIFEST.in -> fcdproc-0.1.2
copying README.md -> fcdproc-0.1.2
copying setup.cfg -> fcdproc-0.1.2
copying setup.py -> fcdproc-0.1.2
copying fcdproc/__init__.py -> fcdproc-0.1.2/fcdproc
copying fcdproc/cli.py -> fcdproc-0.1.2/fcdproc
copying fcdproc.egg-info/PKG-INFO -> fcdproc-0.1.2/fcdproc.egg-info
copying fcdproc.egg-info/SOURCES.txt -> fcdproc-0.1.2/fcdproc.egg-info
copying fcdproc.egg-info/dependency_links.txt -> fcdproc-0.1.2/fcdproc.egg-info
copying fcdproc.egg-info/entry_points.txt -> fcdproc-0.1.2/fcdproc.egg-info
copying fcdproc.egg-info/requires.txt -> fcdproc-0.1.2/fcdproc.egg-info
copying fcdproc.egg-info/top_level.txt -> fcdproc-0.1.2/fcdproc.egg-info
copying fcdproc/interfaces/FCD_preproc.py -> fcdproc-0.1.2/fcdproc/interfaces
copying fcdproc/interfaces/FCD_python.py -> fcdproc-0.1.2/fcdproc/interfaces
copying fcdproc/interfaces/__init__.py -> fcdproc-0.1.2/fcdproc/interfaces
copying fcdproc/utils/__init__.py -> fcdproc-0.1.2/fcdproc/utils
copying fcdproc/utils/misc.py -> fcdproc-0.1.2/fcdproc/utils
copying fcdproc/workflow/__init__.py -> fcdproc-0.1.2/fcdproc/workflow
copying fcdproc/workflow/anatomical.py -> fcdproc-0.1.2/fcdproc/workflow
copying fcdproc/workflow/base.py -> fcdproc-0.1.2/fcdproc/workflow
copying fcdproc/workflow/modeling.py -> fcdproc-0.1.2/fcdproc/workflow
Writing fcdproc-0.1.2/setup.cfg
creating dist
Creating tar archive
removing 'fcdproc-0.1.2' (and everything under it)
running bdist_wheel
running build
running build_py
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/fcdproc
creating build/bdist.linux-x86_64/wheel/fcdproc/utils
copying build/lib/fcdproc/utils/__init__.py -> build/bdist.linux-x86_64/wheel/fcdproc/utils
copying build/lib/fcdproc/utils/misc.py -> build/bdist.linux-x86_64/wheel/fcdproc/utils
copying build/lib/fcdproc/__init__.py -> build/bdist.linux-x86_64/wheel/fcdproc
creating build/bdist.linux-x86_64/wheel/fcdproc/interfaces
copying build/lib/fcdproc/interfaces/FCD_preproc.py -> build/bdist.linux-x86_64/wheel/fcdproc/interfaces
copying build/lib/fcdproc/interfaces/__init__.py -> build/bdist.linux-x86_64/wheel/fcdproc/interfaces
copying build/lib/fcdproc/interfaces/FCD_python.py -> build/bdist.linux-x86_64/wheel/fcdproc/interfaces
copying build/lib/fcdproc/cli.py -> build/bdist.linux-x86_64/wheel/fcdproc
creating build/bdist.linux-x86_64/wheel/fcdproc/workflow
copying build/lib/fcdproc/workflow/__init__.py -> build/bdist.linux-x86_64/wheel/fcdproc/workflow
copying build/lib/fcdproc/workflow/base.py -> build/bdist.linux-x86_64/wheel/fcdproc/workflow
copying build/lib/fcdproc/workflow/modeling.py -> build/bdist.linux-x86_64/wheel/fcdproc/workflow
copying build/lib/fcdproc/workflow/anatomical.py -> build/bdist.linux-x86_64/wheel/fcdproc/workflow
running install_egg_info
Copying fcdproc.egg-info to build/bdist.linux-x86_64/wheel/fcdproc-0.1.2-py3.9.egg-info
running install_scripts
adding license file "LICENSE.txt" (matched pattern "LICENSE.txt")
creating build/bdist.linux-x86_64/wheel/fcdproc-0.1.2.dist-info/WHEEL
creating 'dist/fcdproc-0.1.2-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'fcdproc/__init__.py'
adding 'fcdproc/cli.py'
adding 'fcdproc/interfaces/FCD_preproc.py'
adding 'fcdproc/interfaces/FCD_python.py'
adding 'fcdproc/interfaces/__init__.py'
adding 'fcdproc/utils/__init__.py'
adding 'fcdproc/utils/misc.py'
adding 'fcdproc/workflow/__init__.py'
adding 'fcdproc/workflow/anatomical.py'
adding 'fcdproc/workflow/base.py'
adding 'fcdproc/workflow/modeling.py'
adding 'fcdproc-0.1.2.dist-info/LICENSE.txt'
adding 'fcdproc-0.1.2.dist-info/METADATA'
adding 'fcdproc-0.1.2.dist-info/WHEEL'
adding 'fcdproc-0.1.2.dist-info/entry_points.txt'
adding 'fcdproc-0.1.2.dist-info/top_level.txt'
adding 'fcdproc-0.1.2.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Uploading to PyPI
debug: upload_to_pypi(, path='dist', skip_existing=False, glob_patterns=None)
error: Missing credentials for uploading to PyPI
```

**Comment by ukalwa** [comment]
Looks like you are missing pypi credentials. Please refer to the documentation https://python-semantic-release.readthedocs.io/en/latest/#releasing-on-pypi
You can add the token as a secret to your github repo and set it in the `env` section

**Comment by JanMate** [comment]
@ShervinAbd92, I'm not sure if it really impacts it but check [this](https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html) out and try. From my point of view, you should replace env vars by input parameters - with property. Then you get:
```
with:
  github_token: ${{ secrets.GITHUB_TOKEN }}
  repository_username: __token__
  repository_password: ${{ secrets.PYPI_TOKEN }}
```

Hope it will help you. ✌🏽
