### ISSUE TITLE
semantic-release publish doesnt work at the Github Actions

### ISSUE THREAD

**Issue by kinhosz** [relekang/python-semantic-release#406]
## The problem

Im tring to run this action:

```yml
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with unittest
        working-directory: ./app
        run: python -m unittest discover tests
    
  Release:
    needs: Quality
    # https://github.community/t/how-do-i-specify-job-dependency-running-in-another-workflow/16482
    #if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Semantic Release
        run: |
          pip install python-semantic-release
          git config user.name github-actions
          git config user.email github-actions@github.com
          semantic-release publish
```
but i got the following error:

```
Collecting tomli>=1.0.0
  Downloading tomli-2.0.0-py3-none-any.whl (12 kB)
Collecting packaging>=20.0
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages (from setuptools_scm->dotty-dict<2,>=1.3.0->python-semantic-release) (58.1.0)
Collecting six>=1.9.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting webencodings
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.6-py3-none-any.whl (97 kB)
Collecting cryptography>=2.0
  Downloading cryptography-36.0.1-cp36-abi3-manylinux_2_24_x86_64.whl (3.6 MB)
Collecting cffi>=1.12
  Downloading cffi-1.15.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (444 kB)
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
Using legacy 'setup.py install' for dotty-dict, since package 'wheel' is not installed.
Installing collected packages: pycparser, pyparsing, cffi, zipp, webencodings, urllib3, six, packaging, jeepney, idna, cryptography, charset-normalizer, certifi, tomli, smmap, SecretStorage, requests, Pygments, importlib-metadata, docutils, bleach, tqdm, setuptools-scm, rfc3986, requests-toolbelt, readme-renderer, pkginfo, keyring, gitdb, colorama, click, wheel, twine, tomlkit, semver, python-gitlab, invoke, gitpython, dotty-dict, click-log, python-semantic-release
    Running setup.py install for dotty-dict: started
    Running setup.py install for dotty-dict: finished with status 'done'
Successfully installed Pygments-2.11.2 SecretStorage-3.3.1 bleach-4.1.0 certifi-2021.10.8 cffi-1.15.0 charset-normalizer-2.0.10 click-8.0.3 click-log-0.3.2 colorama-0.4.4 cryptography-36.0.1 docutils-0.18.1 dotty-dict-1.3.0 gitdb-4.0.9 gitpython-3.1.26 idna-3.3 importlib-metadata-4.10.1 invoke-1.6.0 jeepney-0.7.1 keyring-23.5.0 packaging-21.3 pkginfo-1.8.2 pycparser-2.21 pyparsing-3.0.6 python-gitlab-2.10.1 python-semantic-release-7.23.0 readme-renderer-32.0 requests-2.27.1 requests-toolbelt-0.9.1 rfc3986-2.0.0 semver-2.13.0 setuptools-scm-6.4.0 six-1.16.0 smmap-5.0.0 tomli-2.0.0 tomlkit-0.7.0 tqdm-4.62.3 twine-3.7.1 urllib3-1.26.8 webencodings-0.5.1 wheel-0.37.1 zipp-3.7.0
error: Cmd('git') failed due to: exit code(1)
error:   cmdline: git checkout master
error:   stderr: 'error: pathspec 'master' did not match any file(s) known to git'
Error: Process completed with exit code 1
```

## Expected behavior

publish a new release into my github repo, but this doesnt work 😭

**Comment by danth** [comment]
Python Semantic Release has a pre-made Actions step which you can use:
https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html
Please could you try this and report whether the issue still occurs?

**Comment by kinhosz** [comment]
I fix the problem using the following workflow:

```yml
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with unittest
        working-directory: ./app
        run: python -m unittest discover tests
    
  release:
    needs: Quality
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install poetry --upgrade pip
          poetry config virtualenvs.create false
          poetry install
      # Can't use: relekang/python-semantic-release@master because
      # it's running Python 3.7, and Tryceratops requires >=3.8
      - name: Python Semantic Release
        run: |
          pip install python-semantic-release
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          semantic-release publish -D commit_author="github-actions <action@github.com>"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

Thank you for your answer! ❤️
