### ISSUE TITLE
Can't publish from branch `main` with GitHub Action

### ISSUE THREAD

**Issue by H0R5E** [relekang/python-semantic-release#409]
## The problem

For some reason I can not get the python-semantic-release github action to work on my `main` branch. My workflow looks like this:

```yaml
name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Publish the package
    runs-on: ubuntu-latest
    env:
      conda-directory: ${{ github.workspace }}/.conda
    if: github.repository == 'H0R5E/SNL-Delft3D-CEC-Verify'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        lfs: 'true'
        ref : 'main'
        token: ${{ secrets.ADMIN_TOKEN }}
    - name: Expose git commit data
      uses: rlespinasse/git-commit-data-action@v1
    - name: Wait for tests to succeed
      uses: lewagon/wait-on-check-action@v1.0.0
      with:
        ref: ${{ github.ref }}
        running-workflow-name: 'Publish the package'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
      if: env.GIT_COMMIT_COMMITTER_NAME != 'github-actions'
    - name: Set up Git-LFS
      run: |
        sudo apt-get update && sudo apt-get install git-lfs
      if: env.GIT_COMMIT_COMMITTER_NAME != 'github-actions'
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.ADMIN_TOKEN }}
      if: env.GIT_COMMIT_COMMITTER_NAME != 'github-actions'
```

And my configuration in pyproject.toml looks like this:

```toml
[tool.semantic_release]
branch = "main"
version_pattern = [
    'setup.cfg:version = (\d+\.\d+\.\d+)',
    '.conda/recipe/meta.yaml:{{% set version = "(\d+\.\d+\.\d+)" %}}'
]
commit_parser = "semantic_release.history.emoji_parser"
upload_to_repository = "false"
```

But, when I run the job it tries to get the `main` branch again and errors:

```
...
debug: Running publish on branch main
debug: checkout(main)
error: Cmd('git') failed due to: exit code(128)
error:   cmdline: git checkout main
error:   stderr: 'git-lfs filter-process: 1: git-lfs: not found
error: fatal: the remote end hung up unexpectedly'
```

## Expected behavior

I don't understand why python-semantic-release is trying to check out the `main` branch again. I wondered if it was an issue with LFS, but installing LFS in the runner doesn't seem to make it available to python-semantic-release.

## Additional context

If I take away the `branch` variable in the configuration then it tries to check out `master`:

```
debug: Running publish on branch master
debug: checkout('master')
error: Cmd('git') failed due to: exit code(1)
error:   cmdline: git checkout master
error:   stderr: 'error: pathspec 'master' did not match any file(s) known to git'
```
