### ISSUE TITLE
Prelease in github action

### ISSUE THREAD

**Issue by aroder** [relekang/python-semantic-release#425]
How can I do a prerelease from a github action?

```
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}
```
