### ISSUE TITLE
GitHub action should generate variables for later stages

### ISSUE THREAD

**Issue by alandtse** [relekang/python-semantic-release#512]
## Description

*A clear and concise description of your idea.*

Using the GitHub action, `relekang/python-semantic-release@master`, we should set some environment variables for later stages to use. For example:

- release created?
- old version
- new version
- changelog - Just the new section
- release link

## Use cases

*List some reasons this would be useful.*

Later stages could use this information such as if there's a need to publish to repos beyond what is built in.

## Possible implementation

*Describe any ideas you have for how this could work.*
I haven't looked at GitHub action syntax, but this seems like we can gather all the info easily even with existing command options and just populate or document the environment variables.
Compare with [JS semantic release.](https://github.com/marketplace/actions/action-for-semantic-release#outputs)

**Comment by wyardley** [comment]
Seems like this is partially implemented, though not exactly as described above:
```yaml
outputs:
  released:
    description: |
      "true" if a release was made, "false" otherwise

  version:
    description: |
      The newly released version if one was made, otherwise the current version

  tag:
    description: |
      The Git tag corresponding to the version output
```

so the `released` output would be a string of the bool (true / false), and there's a single `version` output vs. one for the cut version and one if a version wasn't cut -- but should be possible to do useful stuff with the combination of `$version` and `$released` anyway.

I _think_ the release link could be generated from the version # and / or tag outputs pretty trivially, since those are usually predictable?

New section of the changelog IMO is maybe a bit less ideal as an output, just because it's so large and irregular.
