### ISSUE TITLE
CLI option to check and fix incorrect commit messages

### ISSUE THREAD

**Issue by Rizhiy** [relekang/python-semantic-release#833]
## Description

Add extra options to check commit message style and also to fix incorrect messages.

## Use cases

I have versioning enabled on main branch, but it breaks if any of the commits don't follow the style.
I would like to add an action to CI to check that all commits since last version are in correct style, so I can check that MR won't break versioning.

Also, I would like to be able to fix incorrect commits locally, probably by using rebase+reword functionality.

## Possible implementation

1. List all commit messages since last ~~commit~~ version
2. Check that each message follows style
3. Call rebase and mark wrong messages for reword

**Comment by codejedi365** [comment]
> Add extra options to check commit message style and also to fix incorrect messages.

Thank you for your input! I can understand why you would want something like this. I have faced and solved similar problems like this for teams. Luckily, It is a solved problem.

> I would like to add an action to CI to check that all commits since last version are in correct style, so I can check that MR won't break versioning.

If you are using angular, I highly recommend looking into the GitHub App Conventional Commits as one way to enforce commit standards. My personal recommendation is to use commitizen (there is a JS and Python variant, but I am talking about `commitizen.py` here). Not only does it provide an interactive cli for making messages (add it as a commit hook) but it can be called with the `check` option and it will validate a range of commits. I personally use the check options for checking any PRs from the CI to prevent invalid messages from getting into the repo. I also use it as a git commit-msg hook to enforce upon commit.

If you are using another parser type or a custom one, please let me know. I'm not sure if there are already built validators out there.

> Also, I would like to be able to fix incorrect commits locally, probably by using rebase+reword functionality.

This is a very complicated problem within git as it must rebuild streams of commits. I have scripted something like this before and it is non-trivial. for that reason, I think is outside of the scope of Semantic Release.   

Generally, PSR focuses on interpreting versions based on standards and creating releases. This type of requirement would be a pivot towards enforcing or fixing standards.

I recommend putting in safeguards via CI verification on PRs for commit linting, and also at the local git hook level. This prevents poorly styled commits into the repo. The one hole is the Web IDE, and direct pushes to main (trunk based dev) but those are organizational management items. These components should solve most of the issue in my opinion as it has for my teams. Let me know what you think.

One other component you could consider is using the following command to provide a bit of a check on version determination. This command will throw a non-zero exit code if a version is not going to be released.

```python
semantic-release --strict version --print
```

Ultimately, I think other tools handle solving this problem already and seems kinda duplicative to add this additional functionality. I say this because our two tools already complement each other as we implement the same conventional commit standard.

**Comment by wyardley** [comment]
Agree with the above - I don't think this tool itself fixing / rewording messages in the past history makes sense. That said, since it's so disruptive and messy to have force-pushes to default branches, it's always wise to try to get people to follow the right conventions from the start (using CI checks). You may also find that using tools like commitizen (as mentioned above) locally might help people follow the convention.

In addition to https://github.com/marketplace/actions/conventional-commits-pr (mentioned above), I've used https://github.com/amannn/action-semantic-pull-request/ in the past.

If you're using GitHub in particular, you may want to consider switching away from the default (which, I think will use the subject and body from the commit message when squash merging if there's only one commit in a PR, but the subject from the PR title if there is >1 commit) to one of the two new options that allow you to force using the PR title when merging. Also, enforcing linear history on whatever default branch you're merging into may be worth considering if it lines up with your workflow (for a gitflow type setup, I'd squash merge into the shared branch but still do regular merge commits into trunk).

There are other tools (like "release-it") that have some ways of working that are a little more flexible, but for semantic-release to work, it relies on the commits both following the convention and being coded correctly.

**Comment by codejedi365** [comment]
Still in backlog

**Comment by codejedi365** [comment]
Still in backlog

**Comment by codejedi365** [comment]
No update, still in backlog

**Comment by codejedi365** [comment]
Still in backlog

**Comment by SiegeSailor** [comment]
I was wondering if PSR can be used as a commit message linting tool, and found this issue (after quite a search and trials). [https://github.com/opensource-nepal/commitlint](https://github.com/opensource-nepal/commitlint) is another tool that provides GitHub Action in CI and a remote Git hook.

> One other component you could consider is using the following command to provide a bit of a check on version determination. This command will throw a non-zero exit code if a version is not going to be released.
> ```shell
> semantic-release version --print --strict
> ```

Thanks to @codejedi365's explanation and solution. Just a quick follow-up for version `10.4.1` here. This command would give you `Error: No such option: --strict Did you mean --print?`. I used `semantic-release --strict version --print` instead. Although I can't really get it to work as a pre-commit tool:

```shell
root % git commit -m "Add"
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/user/.cache/pre-commit/patch1762648277-53482.
semantic-release version check...........................................Passed
[INFO] Restored changes from /Users/user/.cache/pre-commit/patch1762648277-53482.
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/user/.cache/pre-commit/patch1762648277-53527.
semantic-release version check...........................................Passed
[INFO] Restored changes from /Users/user/.cache/pre-commit/patch1762648277-53527.
[release cd931e2] Add
 2 files changed, 7 insertions(+), 6 deletions(-)
root % semantic-release --config "./releaserc.toml" --strict version --print
1.0.0-release.8
```

<details>
<summary>My <code>.pre-commit-config.yaml</code>:</summary>

```yaml
repos:
  - repo: local
    hooks:
      - id: semantic-release-check
        name: semantic-release version check
        entry: semantic-release --config "./releaserc.toml" --strict version --print
        language: system
        stages: [pre-commit]
        pass_filenames: false
        always_run: true
```

</details>

<details>
<summary>My <code>releaserc.toml</code>:</summary>

```toml
[semantic_release]
allow_zero_version = false
assets = ["./README.md", "./notebooks.zip"]
build_command = ""
build_command_env = []
commit_message = """\
chore: release {version}

Automatically generated by python-semantic-release
"""
commit_parser = "conventional"
logging_use_named_masks = false
major_on_zero = true
no_git_verify = false
tag_format = "{version}"
version_toml = []

[semantic_release.commit_author]
default = "semantic-release <semantic-release>"
env = "GIT_COMMIT_AUTHOR"

[semantic_release.branches.main]
match = "(main)"
prerelease = false
prerelease_token = ""

[semantic_release.branches.release]
match = "(release)"
prerelease = true
prerelease_token = "release"

[semantic_release.changelog]
exclude_commit_patterns = []
insertion_flag = "<!-- version list -->"
mode = "update"
template_dir = "templates"

[semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG.md"
output_format = "md"
mask_initial_release = true

[semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = false

[semantic_release.commit_parser_options]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
other_allowed_tags = ["build", "chore", "ci", "docs", "style", "refactor", "test"]
allowed_tags = ["feat", "fix", "perf", "build", "chore", "ci", "docs", "style", "refactor", "test"]
default_bump_level = 0
parse_squash_commits = true
ignore_merge_commits = true

[semantic_release.remote]
name = "origin"
type = "github"
ignore_token_for_push = false
insecure = false

[semantic_release.publish]
dist_glob_patterns = ["./dist/*"]
upload_to_vcs_release = true
```

</details>
